#server:
#  port: ${port}
#  context-path: /client1

systemName : systemName
server:
  port : 8090

spring.h2.console:
  enabled: true
  path: /h2-console

logging.level:
  root: warn
  org.springframework:
    boot: info
  com.oauth.sso.client: debug